import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const styleBanner =
`/* Generated file. Do not edit directly. Edit files in src/styles instead. This file will be overwritten upon each build. */
`;

const prod = (process.argv[2] === "production");

const scriptContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	loader: {
		".wasm": "binary",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: ".",
	entryNames: "[name]",
	minify: prod,
});

const styleContext = await esbuild.context({
	banner: {
		css: styleBanner,
	},
	entryPoints: {
		styles: "src/styles/index.css",
	},
	bundle: true,
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outdir: ".",
	entryNames: "[name]",
	minify: false,
});

if (prod) {
	await Promise.all([scriptContext.rebuild(), styleContext.rebuild()]);
	await Promise.all([scriptContext.dispose(), styleContext.dispose()]);
	process.exit(0);
} else {
	await Promise.all([scriptContext.watch(), styleContext.watch()]);
}
