import { PromptTemplate } from "../types/PromptTemplate";

const BUILT_IN_TEMPLATE_CREATED_AT = "2026-01-01T00:00:00.000Z";

export const DEFAULT_PROMPT_TEMPLATES: PromptTemplate[] = [
	{
		id: "fix-spelling-and-grammar",
		name: "Fix spelling and grammar",
		description: "Correct spelling, grammar, and punctuation without changing the meaning.",
		scope: "selection",
		prompt: [
			"Correct only clear spelling, grammar, punctuation, capitalisation, and obvious typo errors in the selected text.",
			"Preserve the original wording, sentence structure, rhythm, tone, and meaning as much as possible.",
			"Do not rewrite sentences for style or clarity.",
			"Do not replace words with synonyms unless the original word is clearly incorrect.",
			"Do not improve the prose beyond correcting actual errors.",
			"Do not summarise, explain, critique, introduce, or comment on the correction.",
			"Do not wrap the answer in quotes.",
			"Do not add headings.",
			"Return only the corrected text.",
		].join("\n"),
		returnsReplacementTextOnly: true,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},

	{
		id: "make-clearer",
		name: "Make clearer",
		description: "Rewrite the selected text so it is easier to understand while keeping the meaning.",
		scope: "selection",
		prompt: [
			"Rewrite the selected text to make it clearer and easier to understand.",
			"Keep the original meaning.",
			"Keep the author's voice where possible.",
			"Do not add new ideas unless needed for clarity.",
			"Return only the rewritten text with no explanation.",
		].join("\n"),
		returnsReplacementTextOnly: true,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},

	{
		id: "summarise",
		name: "Summarise",
		description: "Create a concise summary of the selected text.",
		scope: "selection",
		prompt: [
			"Summarise the selected text clearly and concisely.",
			"Keep the key points and important details.",
			"Do not add new information that is not present in the selected text.",
			"Return only the summary with no extra explanation.",
		].join("\n"),
		returnsReplacementTextOnly: false,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},

	{
		id: "critique",
		name: "Critique",
		description: "Review the selected text and point out strengths, weaknesses, and possible improvements.",
		scope: "selection",
		prompt: [
			"Critique the selected text clearly and constructively.",
			"Identify what works well.",
			"Identify what is unclear, weak, repetitive, or missing.",
			"Suggest practical improvements.",
			"Do not rewrite the whole text unless the user asks for that.",
		].join("\n"),
		returnsReplacementTextOnly: false,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},
	{
		id: "continue-writing",
		name: "Continue writing",
		description: "Continue from the selected text using the user's direction.",
		scope: "selection",
		prompt: [
			"Continue writing from the selected text.",
			"Use the selected text as the immediate lead-in.",
			"Follow the user's direction for what should happen next.",
			"Match the existing tone, style, pacing, and point of view where possible.",
			"Do not repeat or rewrite the selected text.",
			"Only write the new continuation.",
		].join("\n"),
		returnsReplacementTextOnly: false,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},
	{
		id: "rewrite-in-same-voice",
		name: "Rewrite in same voice",
		description: "Rewrite the selected text while preserving the author's style and tone.",
		scope: "selection",
		prompt: [
			"Rewrite the selected text while keeping the same voice, tone, and meaning.",
			"Improve clarity and flow where useful.",
			"Do not make the text sound like a different author.",
			"Return only the rewritten text with no explanation.",
		].join("\n"),
		returnsReplacementTextOnly: true,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},

	{
		id: "extend-from-selection",
		name: "Extend from selection",
		description: "Continue from the selected text using the user's direction.",
		scope: "selection",
		prompt: [
			"Continue writing from the selected text.",
			"Use the selected text as the immediate lead-in.",
			"Follow the user's direction for what should happen next.",
			"Match the existing tone, style, pacing, and point of view where possible.",
			"Do not repeat or rewrite the selected text.",
			"Return only the new continuation.",
		].join("\n"),
		returnsReplacementTextOnly: false,
		isBuiltIn: true,
		createdAt: BUILT_IN_TEMPLATE_CREATED_AT,
		updatedAt: BUILT_IN_TEMPLATE_CREATED_AT,
	},
];
